### ISSUE TITLE
The project's future

### ISSUE THREAD

**Issue by befeleme** [frenzymadness/specfile_generator#11]
_This issue is a big container of random thoughts that could (and probably should) be parsed to smaller units when discussed._

Hey,
I took a look at specfile generator while attempting to create new Python packages. 
The results were quite good: the resulting packages could be built as-is. 
As pyproject macros developed in the last years, there are quite a few things that can be changed.

I have a load of comments regarding the specfile, but haven't yet really looked at the code.
**Functionality**
- no need to enable dependency generator anymore
- call `%pyproject_save_files` and use saved files in `%files` section
- discover `%doc` and `%license` if it's deterministic

**Cosmetics**
- script's output could be improved - it's rather shocking that something is downloaded and installed (where to? do I have to uninstall it?)
- Source0 might be improved to `%{pypi source}`
- Description - shorted, with wrapped lines, or at least defined once in a macro
- BR on `python3-devel` can be moved higher, listed together with `pyproject-rpm-macros`
- I'd remove development todo comments from the spec file in favor of issues here, leave commented out only the things that a person should fill in (like `%license`, `%doc`, unless they're discovered automatically)
- filename heuristics (always prepend with "python-"? if not, on what conditions?)
- find better name for the project and script? :)

**To discuss - check section / output philosophy**
If the aim is to generate a file that in vast majority allows us to generate at least some rpm + the tarball is downloaded from PyPI, there is a big chance that
- no tests are shipped
- test dependencies aren't packaged in Fedora
- test dependencies aren't desired in Fedora (coverage, linters...)
which breaks the build initially, i.e. it's better not to try to implement a logic for that.
Alternatively, once `%py3_check_import` is available, we can consider enabling it if we can reasonably determine module name.

I'd love to discuss how to approach directions of possible project development from its philosophy to future distribution method(s). 
@frenzymadness, would you like to discuss it with me and mentor the project?

**Comment by encukou** [comment]
> frenzymadness, would you like to discuss it with me and mentor the project?

I could do that as well.

I agree with everything here

> script's output could be improved - it's rather shocking that something is downloaded and installed (where to? do I have to uninstall it?)

Perhaps the list of modules (and binaries) could be taken from a *wheel* instead?

**Comment by frenzymadness** [comment]
This project really needs some love if we want to use it in the future. I also agree with your point of view. New macros make it much easier.

**Comment by frenzymadness** [comment]
I'm gonna archive this project with a link to https://github.com/befeleme/pyp2spec
